apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-apps/app/overlay-local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # this references the GitRepository resource which points to the actual Git Repo

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-infra/overlay-local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # this references the GitRepository resource which points to the actual Git Repo