apiVersion: v1
kind: Namespace
metadata:
  name: external-dns

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  url: oci://registry-1.docker.io/bitnamicharts
#  type: "oci"

---

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: v9.0.2
      interval: 10m0s # this is the interval for checking the chart i.e. version
      sourceRef:
        kind: HelmRepository
        name: external-dns
  releaseName: external-dns
  targetNamespace: external-dns # this is where to deploy the resources
  interval: 10m0s # this is the interval for checking the release i.e. deployment of the chart
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values