apiVersion: v1
kind: Namespace
metadata:
  name: headlamp

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: headlamp
spec:
  url: https://kubernetes-sigs.github.io/headlamp/

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  chart:
    spec:
      chart: headlamp
      version: v0.36.0
      interval: 10m0s # this is the interval for checking the chart i.e. version
      sourceRef:
        kind: HelmRepository
        name: headlamp
  releaseName: headlamp
  targetNamespace: headlamp # this is where to deploy the resources
  interval: 10m0s # this is the interval for checking the release i.e. deployment of the chart
  valuesFrom:
    - kind: ConfigMap
      name: headlamp-values