apiVersion: v1
kind: Namespace
metadata:
  name: karpenter

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: karpenter
  namespace: karpenter
spec:
  type: "oci"
  url: oci://public.ecr.aws/karpenter/

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  chart:
    spec:
      chart: karpenter
      version: 1.8.2
      interval: 10m0s # this is the interval for checking the chart i.e. version
      sourceRef:
        kind: HelmRepository
        name: karpenter
  releaseName: karpenter
  targetNamespace: karpenter # this is where to deploy the resources
  interval: 10m0s # this is the interval for checking the release i.e. deployment of the chart
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: karpenter-values