apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  url: https://kubernetes.github.io/ingress-nginx

---

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.3
      interval: 10m0s # this is the interval for checking the chart i.e. version
      sourceRef:
        kind: HelmRepository
        name: nginx
  releaseName: ingress-nginx # this is where to deploy the resources
  targetNamespace: nginx
  interval: 10m0s # this is the interval for checking the release i.e. deployment of the chart