apiVersion: v1
kind: Namespace
metadata:
  name: monitor

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prom-graf
  namespace: monitor
spec:
  url: https://prometheus-community.github.io/helm-charts

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-graf
  namespace: monitor
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: v78.3.2
      interval: 10m0s # this is the interval for checking the chart i.e. version
      sourceRef:
        kind: HelmRepository
        name: prom-graf
  releaseName: prom-graf
  targetNamespace: monitor # this is where to deploy the resources
  interval: 10m0s # this is the interval for checking the release i.e. deployment of the chart
  valuesFrom:
    - kind: ConfigMap
      name: prom-graf-values