apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory" # the following is the production server: "https://acme-v02.api.letsencrypt.org/directory" and following is the staging server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: "junedwork@hotmail.com"
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53: {} # remove these {} if you want to explicitely specify the hostedZoneID and region here
#          hostedZoneID: xxxxxxxxxxxxxxxxxxx #this must be updated with the current hostedZoneID in order for it to work
#          region: xxxxxxxxxxx
      selector:
        dnsZones:
        - "lab.juned.co.uk"
    - http01:
        ingress:
          class: nginx