apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
  namespace: myapp-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 677276074604.dkr.ecr.eu-west-2.amazonaws.com/to-do-app
        ports:
        - containerPort: 8080