apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: myapp-ns
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 # i.e. the container port
  type: ClusterIP