provider: aws

policy: sync # this will create and delete the records within Route 53

# env: # this is the old way of doing it
# - name: AWS_DEFAULT_REGION
#   value: eu-west-2

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "EXTERNAL_DNS_ROLE_ARN" # This will be replaced by Kustomize

aws:
  region: eu-west-2

domainFilters:
- lab.juned.co.uk # needed otherwise it will have the ability to create records for any domain
