apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: clustersecretstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: dockerhub-secret # this is the name of the secret to be created
    creationPolicy: Owner
  data:
  - secretKey: username # this is the key of the secret to be created
    remoteRef:
      key: dockerhub-credentials # this is the key of the secret in AWS Secrets Manager
      property: username # this is the property of the secret in AWS Secrets Manager
  - secretKey: password # this is the key of the secret to be created
    remoteRef:
      key: dockerhub-credentials # this is the key of the secret in AWS Secrets Manager
      property: password # this is the property of the secret in AWS Secrets Manager