apiVersion: external-secrets.io/v1
kind: ClusterSecretStore # kept it simple and made it clusterwide so ExternalSecret can be created in any namespace
metadata:
  name: clustersecretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2

---

# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: dockerhub-secret
#   namespace: external-dns
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     name: clustersecretstore
#     kind: ClusterSecretStore
#   target:
#     name: dockerhub-secret # this is the name of the secret to be created
#     creationPolicy: Owner
#   data:
#   - secretKey: username # this is the key of the secret to be created
#     remoteRef:
#       key: dockerhub-credentials # this is the key of the secret in AWS Secrets Manager
#       property: username # this is the property of the secret in AWS Secrets Manager
#   - secretKey: password # this is the key of the secret to be created
#     remoteRef:
#       key: dockerhub-credentials # this is the key of the secret in AWS Secrets Manager
#       property: password # this is the property of the secret in AWS Secrets Manager