apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
configMapGenerator: # I chose the configMap way to input the values as it allows for flux to redeploy the resources if the values change
  - name: prom-graf-values
    namespace: monitor # needed in order for configmap to be created in the correct namespace
    files:
      - values.yaml=values/prom-graf-values.yml
  - name: external-dns-values
    namespace: external-dns # needed in order for configmap to be created in the correct namespace
    files:
      - values.yaml=values/external-dns-values.yml
  - name: cert-manager-values
    namespace: cert-manager # needed in order for configmap to be created in the correct namespace
    files:
      - values.yaml=values/cert-manager-values.yml
configurations:
  - kustomizeconfig.yml

  # looking at this retrospectively, I could have avoided configmap and used a patch in this file to input the values.yml