installCRDs: true # default value is true but it's better to be explicit

serviceAccount:
  create: true
  name: external-secrets
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::677276074604:role/external-secrets-role
  extraLabels: {}