
serviceAccount:
  create: true # default is true
  name: headlamp-admin
  annotations: {}

ingress:
  enabled: true # default is false
  ingressClassName: "nginx"
  hosts:
    - headlamp.lab.juned.co.uk
  tls:
    - secretName: headlamp-ingress-tls
      hosts:
      - headlamp.lab.juned.co.uk

securityContext:
  runasNonRoot: true # default is true
  privilged: false # default is false

clusterRoleBinding:
  create: true # default is true
  clusterRoleName: "cluster-admin" # default is "cluster-admin" # test out the "view" role