serviceAccount:
  create: true # default is true
  name: "headlamp-admin"
  annotations: {}

ingress:
  enabled: true # default is false
  ingressClassName: "nginx"
  hosts:
    - host: headlamp.lab.juned.co.uk
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-ingress-tls
      hosts:
        - headlamp.lab.juned.co.uk

securityContext:
  runAsNonRoot: true # default is true
  privileged: false # default is false

clusterRoleBinding:
  create: true # default is true
  clusterRoleName: view" # default is "cluster-admin" # test out the "view" role