config:
  oidc:
    secret:
      create: false # default is true
  enableHelm: true # default is true
  watchPlugins: true # defualt is false
  pluginsDir: /build/plugins

serviceAccount:
  create: true # default is true
  name: "headlamp-admin"
  annotations: {}

ingress:
  enabled: true # default is false
  ingressClassName: "nginx"
  hosts:
    - host: headlamp.lab.juned.co.uk
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-ingress-tls
      hosts:
        - headlamp.lab.juned.co.uk

securityContext:
  runAsNonRoot: true # default is true
  privileged: false # default is false

clusterRoleBinding:
  create: true # default is true
  clusterRoleName: cluster-admin # default is "cluster-admin" # test out the "view" role



# below is the installation of the flux plugin
# guide https://github.com/headlamp-k8s/plugins/tree/main/flux
# image link https://github.com/headlamp-k8s/plugins/pkgs/container/headlamp-plugin-flux
initContainers:
  - command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
    image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest # using 0.4.0 but mentioning the exact version number tag does not work hence why using "latest" tag
    imagePullPolicy: Always
    name: headlamp-plugins
    securityContext:
      runAsNonRoot: false
      privileged: false
      runAsUser: 0
      runAsGroup: 0
    volumeMounts: # volume mount for the init container
      - mountPath: /build/plugins
        name: headlamp-plugins


#volumes set up that is needed for plugin to work
volumeMounts: # volume mount for the headlamp container
  - mountPath: /build/plugins
    name: headlamp-plugins

volumes:
  - name: headlamp-plugins
    emptyDir: {} # decided to use a temp volume as there is no actual data that I need to be persistent (since the headlamp app only has to use the static files htat the plugin installs on that directory for as long as the headlamp app, i.e. the pod, runs). Empty dir works here only because the headlamp app container and the plugin container exist in the same pod
    # persistentVolumeClaim:
    #   claimName: headlamp # The name of the Helm release